import {
  Badge,
  Button,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Skeleton,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@yres/ui";
import { Wrench } from "lucide-react";
import { useEffect, useState } from "react";
import { useMeasures, useSelectMeasures } from "../../hooks";
import { ApiError } from "../../lib/api";
import { MEASURE_CATEGORY_LABELS, formatNumber } from "../../lib/labels";

export function MeasuresTab({ buildingId }: { buildingId: string }) {
  const { data, isLoading, isError, error } = useMeasures(buildingId, { pageSize: 200 });
  const selectMeasures = useSelectMeasures(buildingId);

  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saved, setSaved] = useState(false);

  const measures = data?.measures ?? [];

  // biome-ignore lint/correctness/useExhaustiveDependencies: intentionally re-syncs local checkbox state only when the server data object changes (e.g. after a fresh fetch or a save), not on every render.
  useEffect(() => {
    setSelected(new Set(measures.filter((m) => m.proposedForImplementation).map((m) => m.id)));
  }, [data]);

  function toggle(id: string) {
    setSaved(false);
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function handleSave() {
    setSaveError(null);
    setSaved(false);
    try {
      await selectMeasures.mutateAsync([...selected]);
      setSaved(true);
    } catch (err) {
      setSaveError(err instanceof ApiError ? err.message : "Failed to save measure selection.");
    }
  }

  if (isLoading) {
    return (
      <div className="space-y-2">
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-10 w-full" />
      </div>
    );
  }

  if (isError) {
    return (
      <Card className="border-destructive/50">
        <CardContent className="p-6 text-sm text-destructive">
          Failed to load measures: {error instanceof ApiError ? error.message : "Unknown error"}
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0">
          <CardTitle className="text-base">Energy measures</CardTitle>
          <Button size="sm" onClick={handleSave} disabled={selectMeasures.isPending}>
            {selectMeasures.isPending ? "Saving..." : "Save selection"}
          </Button>
        </CardHeader>
        <CardContent>
          {measures.length === 0 ? (
            <div className="flex flex-col items-center gap-3 py-10 text-center">
              <Wrench className="h-10 w-10 text-muted-foreground" />
              <p className="font-medium">No measures identified yet</p>
              <p className="max-w-sm text-sm text-muted-foreground">
                Energy measures are generated by running an audit for this building.
              </p>
            </div>
          ) : (
            <>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-10">Proposed</TableHead>
                    <TableHead>Name</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead>Investment (USD)</TableHead>
                    <TableHead>Lifetime (yrs)</TableHead>
                    <TableHead>Maintenance (%)</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {measures.map((measure) => (
                    <TableRow key={measure.id}>
                      <TableCell>
                        <input
                          type="checkbox"
                          className="h-4 w-4 rounded border-input"
                          checked={selected.has(measure.id)}
                          onChange={() => toggle(measure.id)}
                          aria-label={`Propose ${measure.name}`}
                        />
                      </TableCell>
                      <TableCell className="font-medium">{measure.name}</TableCell>
                      <TableCell>
                        <Badge variant="secondary">
                          {MEASURE_CATEGORY_LABELS[measure.category]}
                        </Badge>
                      </TableCell>
                      <TableCell>{formatNumber(measure.investmentCostUsd, 0)}</TableCell>
                      <TableCell>{measure.lifetimeYears}</TableCell>
                      <TableCell>{formatNumber(measure.maintenanceCostPercent, 2)}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              {saveError && <p className="mt-4 text-sm text-destructive">{saveError}</p>}
              {saved && !saveError && (
                <p className="mt-4 text-sm text-success">Measure selection saved.</p>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
