import { expect, test } from "@playwright/test";

/**
 * Verifies the Phase 9 fix end-to-end through the real UI: there was
 * previously no way to create an energy_measure row at all (the Measures
 * tab's empty state even claimed measures "are generated by running an
 * audit," which was never true — AuditEngine only ever reads existing
 * rows). This creates a building and adds a measure via the new "Add a
 * measure" form, confirming it shows up in the list and can be proposed
 * and deleted.
 */
test("adds, proposes, and deletes an energy measure via the Measures tab", async ({ page }) => {
  const unique = Date.now();
  const email = `e2e-measures-${unique}@example.com`;

  await page.goto("/register");
  await page.getByLabel("Full name").fill("E2E Measures User");
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("password1234");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/dashboard$/);

  await page.getByRole("link", { name: "New Building" }).first().click();
  await page.getByLabel("Name *").fill("E2E Measures Building");
  await page.getByLabel("Location *").fill("Tashkent");
  await page.getByLabel("Climate region *").click();
  await page.getByRole("option", { name: "Tashkent" }).click();
  await page.getByLabel("Net cooled floor area (m²)").fill("450");
  await page.getByRole("button", { name: "Create building" }).click();
  await expect(page).toHaveURL(/\/buildings\/[0-9a-f-]+$/);

  await page.getByRole("tab", { name: "Measures" }).click();
  await expect(page.getByText("No measures added yet")).toBeVisible();

  await page.getByLabel("Name").fill("LED lighting retrofit");
  await page.getByLabel("Investment (USD)").fill("4000");
  await page.getByRole("button", { name: "Add measure" }).click();

  await expect(page.getByText("No measures added yet")).toHaveCount(0);
  const row = page.getByRole("row").filter({ hasText: "LED lighting retrofit" });
  await expect(row).toBeVisible();

  await row.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Save selection" }).click();
  await expect(page.getByText("Measure selection saved.")).toBeVisible();

  await row.getByRole("button", { name: /Delete/ }).click();
  await expect(page.getByText("No measures added yet")).toBeVisible();
});
