import { energyMeasure } from "@yres/db";
import { and, eq, inArray, notInArray } from "drizzle-orm";
import type { BatchItem } from "drizzle-orm/batch";
import { Hono } from "hono";
import { canWrite, findAccessibleBuilding } from "../lib/building-access";
import { type AppEnv, authMiddleware } from "../middleware/auth";
import { createMeasureSchema, selectMeasuresSchema } from "../schemas/measures";
import { paginationQuerySchema, toLimitOffset } from "../schemas/pagination";

export const measuresRoutes = new Hono<AppEnv>();

measuresRoutes.use("*", authMiddleware);

// GET /:id/measures - list a building's energy_measure rows, paginated
measuresRoutes.get("/:id/measures", async (c) => {
  const buildingId = c.req.param("id");
  const parsedQuery = paginationQuerySchema.safeParse(c.req.query());
  if (!parsedQuery.success) {
    return c.json({ error: "Invalid query", details: parsedQuery.error.flatten() }, 400);
  }
  const { limit, offset } = toLimitOffset(parsedQuery.data);

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }

  const measures = await db
    .select()
    .from(energyMeasure)
    .where(eq(energyMeasure.buildingId, buildingId))
    .limit(limit)
    .offset(offset);

  return c.json({
    measures,
    page: parsedQuery.data.page,
    pageSize: parsedQuery.data.pageSize,
  });
});

// POST /:id/measures - create an energy_measure row for this building. This
// route was entirely missing before: AuditEngine only ever reads existing
// energy_measure rows (see services/audit.engine.ts), it never creates
// them, so without this a building could never have any measures to select
// or evaluate — the Measures tab's empty state even used to claim measures
// "are generated by running an audit," which was never true.
measuresRoutes.post("/:id/measures", async (c) => {
  const buildingId = c.req.param("id");
  const body = await c.req.json().catch(() => null);
  const parsed = createMeasureSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const [measure] = await db
    .insert(energyMeasure)
    .values({ ...parsed.data, buildingId })
    .returning();

  return c.json({ measure }, 201);
});

// DELETE /:id/measures/:measureId
measuresRoutes.delete("/:id/measures/:measureId", async (c) => {
  const buildingId = c.req.param("id");
  const measureId = c.req.param("measureId");
  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const deleted = await db
    .delete(energyMeasure)
    .where(and(eq(energyMeasure.id, measureId), eq(energyMeasure.buildingId, buildingId)))
    .returning();

  if (deleted.length === 0) {
    return c.json({ error: "Not found" }, 404);
  }

  return c.body(null, 204);
});

// POST /:id/measures/select - set proposedForImplementation = true for the
// given measure ids, and false for the building's other measures. Two UPDATE
// statements executed atomically via db.batch() (see envelope.ts for why not
// db.transaction()).
measuresRoutes.post("/:id/measures/select", async (c) => {
  const buildingId = c.req.param("id");
  const body = await c.req.json().catch(() => null);
  const parsed = selectMeasuresSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const { measureIds } = parsed.data;

  if (measureIds.length === 0) {
    await db
      .update(energyMeasure)
      .set({ proposedForImplementation: false })
      .where(eq(energyMeasure.buildingId, buildingId));

    return c.json({ selected: [] });
  }

  const statements: BatchItem<"pg">[] = [
    db
      .update(energyMeasure)
      .set({ proposedForImplementation: true })
      .where(and(eq(energyMeasure.buildingId, buildingId), inArray(energyMeasure.id, measureIds))),
    db
      .update(energyMeasure)
      .set({ proposedForImplementation: false })
      .where(
        and(eq(energyMeasure.buildingId, buildingId), notInArray(energyMeasure.id, measureIds)),
      ),
  ];

  await db.batch(statements as [BatchItem<"pg">, ...BatchItem<"pg">[]]);

  return c.json({ selected: measureIds });
});
