import { energyMeasure, energyMeasureTarget, insertChunked, nonEeMeasure } from "@yres/db";
import { and, eq, inArray } from "drizzle-orm";
import type { BatchItem } from "drizzle-orm/batch";
import { Hono } from "hono";
import {
  auditEventStatement,
  getRevisions,
  isRevisionConflict,
  revisionConflictResponse,
} from "../lib/audit-event";
import { canWrite, findAccessibleBuilding } from "../lib/building-access";
import { type AppEnv, authMiddleware } from "../middleware/auth";
import {
  createMeasureSchema,
  createNonEeMeasureSchema,
  selectMeasuresSchema,
} from "../schemas/measures";
import { paginationQuerySchema, toLimitOffset } from "../schemas/pagination";

// Leaves headroom under D1's 100-parameter limit for the building-id parameter.
const MEASURE_ID_CHUNK = 90;

export const measuresRoutes = new Hono<AppEnv>();

measuresRoutes.use("*", authMiddleware);

// GET /:id/measures - list a building's energy_measure rows, paginated
measuresRoutes.get("/:id/measures", async (c) => {
  const buildingId = c.req.param("id");
  const parsedQuery = paginationQuerySchema.safeParse(c.req.query());
  if (!parsedQuery.success) {
    return c.json({ error: "Invalid query", details: parsedQuery.error.flatten() }, 400);
  }
  const { limit, offset } = toLimitOffset(parsedQuery.data);

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }

  // `with: { targets }` is folded into the same SQL statement (json subquery) — one D1 query.
  const [measures, revisions] = await Promise.all([
    db.query.energyMeasure.findMany({
      where: eq(energyMeasure.buildingId, buildingId),
      with: { targets: { columns: { kind: true, code: true } } },
      limit,
      offset,
    }),
    // A10: so the measure-selection UI can send it back as `expectedRevision` on POST /select.
    getRevisions(db, buildingId, ["measures"]),
  ]);

  return c.json({
    measures,
    page: parsedQuery.data.page,
    pageSize: parsedQuery.data.pageSize,
    revision: revisions.measures,
  });
});

// POST /:id/measures - create an energy_measure row for this building. This
// route was entirely missing before: AuditEngine only ever reads existing
// energy_measure rows (see services/audit.engine.ts), it never creates
// them, so without this a building could never have any measures to select
// or evaluate — the Measures tab's empty state even used to claim measures
// "are generated by running an audit," which was never true.
measuresRoutes.post("/:id/measures", async (c) => {
  const buildingId = c.req.param("id");
  const body = await c.req.json().catch(() => null);
  const parsed = createMeasureSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  // One atomic batch: the audit event + the measure row + its targets. Budget:
  // 1 (audit) + 1 (measure) + ceil(40 / 25) = 4 statements (targets are capped at 40 in the
  // schema; the target table has 4 columns -> 25 rows per insert).
  const { targets, ...measureFields } = parsed.data;
  const measureId = crypto.randomUUID();
  const statements: BatchItem<"sqlite">[] = [
    auditEventStatement(db, c, {
      buildingId,
      entity: "measures",
      entityId: measureId,
      action: "create",
      summary: { name: measureFields.name, category: measureFields.category },
    }),
    db.insert(energyMeasure).values({ ...measureFields, id: measureId, buildingId }),
    ...insertChunked(
      db,
      energyMeasureTarget,
      targets.map((t) => ({ measureId, kind: t.kind, code: t.code })),
    ),
  ];
  await db.batch(statements as [BatchItem<"sqlite">, ...BatchItem<"sqlite">[]]);

  const measure = await db.query.energyMeasure.findFirst({
    where: eq(energyMeasure.id, measureId),
    with: { targets: { columns: { kind: true, code: true } } },
  });

  return c.json({ measure }, 201);
});

// PUT /:id/measures/:measureId - edit a measure; its targets are replaced as a set. One atomic batch:
// update + delete old targets + chunked insert = 2 + ceil(40 / 25) <= 4 statements.
measuresRoutes.put("/:id/measures/:measureId", async (c) => {
  const buildingId = c.req.param("id");
  const measureId = c.req.param("measureId");
  const body = await c.req.json().catch(() => null);
  const parsed = createMeasureSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const existing = await db.query.energyMeasure.findFirst({
    where: and(eq(energyMeasure.id, measureId), eq(energyMeasure.buildingId, buildingId)),
    columns: { id: true },
  });
  if (!existing) {
    return c.json({ error: "Not found" }, 404);
  }

  const { targets, ...measureFields } = parsed.data;
  const statements: BatchItem<"sqlite">[] = [
    auditEventStatement(db, c, {
      buildingId,
      entity: "measures",
      entityId: measureId,
      action: "update",
      summary: { name: measureFields.name, category: measureFields.category },
    }),
    db
      .update(energyMeasure)
      .set(measureFields)
      .where(and(eq(energyMeasure.id, measureId), eq(energyMeasure.buildingId, buildingId))),
    db.delete(energyMeasureTarget).where(eq(energyMeasureTarget.measureId, measureId)),
    ...insertChunked(
      db,
      energyMeasureTarget,
      targets.map((t) => ({ measureId, kind: t.kind, code: t.code })),
    ),
  ];
  await db.batch(statements as [BatchItem<"sqlite">, ...BatchItem<"sqlite">[]]);

  const measure = await db.query.energyMeasure.findFirst({
    where: eq(energyMeasure.id, measureId),
    with: { targets: { columns: { kind: true, code: true } } },
  });

  return c.json({ measure });
});

// DELETE /:id/measures/:measureId
measuresRoutes.delete("/:id/measures/:measureId", async (c) => {
  const buildingId = c.req.param("id");
  const measureId = c.req.param("measureId");
  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  // Fetched up front (not from the delete's own `.returning()`) because the audit summary has to
  // be known *before* the batch runs — it's the first statement in the same `db.batch()` as the
  // delete (database.md, A09 "Qilmang": no audit row outside the mutation's batch).
  const existing = await db.query.energyMeasure.findFirst({
    where: and(eq(energyMeasure.id, measureId), eq(energyMeasure.buildingId, buildingId)),
    columns: { name: true, category: true, investmentCostUsd: true },
  });
  if (!existing) {
    return c.json({ error: "Not found" }, 404);
  }

  const statements: BatchItem<"sqlite">[] = [
    auditEventStatement(db, c, {
      buildingId,
      entity: "measures",
      entityId: measureId,
      action: "delete",
      summary: existing,
    }),
    db
      .delete(energyMeasure)
      .where(and(eq(energyMeasure.id, measureId), eq(energyMeasure.buildingId, buildingId))),
  ];
  await db.batch(statements as [BatchItem<"sqlite">, ...BatchItem<"sqlite">[]]);

  return c.body(null, 204);
});

// POST /:id/measures/select - set proposedForImplementation = true for the
// given measure ids, and false for the building's other measures. Two UPDATE
// statements executed atomically via db.batch() (see envelope.ts for why not
// db.transaction()).
measuresRoutes.post("/:id/measures/select", async (c) => {
  const buildingId = c.req.param("id");
  const body = await c.req.json().catch(() => null);
  const parsed = selectMeasuresSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const { measureIds, expectedRevision } = parsed.data;

  if (measureIds.length === 0) {
    try {
      await db.batch([
        auditEventStatement(db, c, {
          buildingId,
          entity: "measures",
          action: "update",
          expectedRevision,
          summary: { selectedCount: 0 },
        }),
        db
          .update(energyMeasure)
          .set({ proposedForImplementation: false })
          .where(eq(energyMeasure.buildingId, buildingId)),
      ]);
    } catch (err) {
      if (isRevisionConflict(err)) {
        return revisionConflictResponse(c, db, buildingId, "measures");
      }
      throw err;
    }

    const revision =
      expectedRevision !== undefined
        ? expectedRevision + 1
        : (await getRevisions(db, buildingId, ["measures"])).measures;
    return c.json({ selected: [], revision });
  }

  // D1 binds at most 100 parameters per statement and every id in an IN list counts, so the selection is
  // applied in chunks. One batch (atomic): audit event + clear the building's flags, then set them chunk
  // by chunk. Budget: 1 (audit) + 1 (clear) + ceil(500 ids / 90) = 8 statements (measureIds is capped at
  // 500 in the schema). A10's `expectedRevision` adds no statement; unguarded, +1 query
  // (getRevisions) to report the new revision = 9 ≤ 40.
  const statements: BatchItem<"sqlite">[] = [
    auditEventStatement(db, c, {
      buildingId,
      entity: "measures",
      action: "update",
      expectedRevision,
      summary: { selectedCount: measureIds.length },
    }),
    db
      .update(energyMeasure)
      .set({ proposedForImplementation: false })
      .where(eq(energyMeasure.buildingId, buildingId)),
  ];
  for (let i = 0; i < measureIds.length; i += MEASURE_ID_CHUNK) {
    statements.push(
      db
        .update(energyMeasure)
        .set({ proposedForImplementation: true })
        .where(
          and(
            eq(energyMeasure.buildingId, buildingId),
            inArray(energyMeasure.id, measureIds.slice(i, i + MEASURE_ID_CHUNK)),
          ),
        ),
    );
  }

  try {
    await db.batch(statements as [BatchItem<"sqlite">, ...BatchItem<"sqlite">[]]);
  } catch (err) {
    if (isRevisionConflict(err)) {
      return revisionConflictResponse(c, db, buildingId, "measures");
    }
    throw err;
  }

  const revision =
    expectedRevision !== undefined
      ? expectedRevision + 1
      : (await getRevisions(db, buildingId, ["measures"])).measures;
  return c.json({ selected: measureIds, revision });
});

// GET /:id/non-ee-measures - list a building's non_ee_measure rows (ancillary
// renovation costs — cable replacement, re-plastering, etc.). Only rows with
// proposedForImplementation (v7.20 "Q" column, default true) count toward
// AuditSummary.totalInvestmentUsd (see audit.engine.ts's buildAuditSummary).
measuresRoutes.get("/:id/non-ee-measures", async (c) => {
  const buildingId = c.req.param("id");
  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }

  const rows = await db.select().from(nonEeMeasure).where(eq(nonEeMeasure.buildingId, buildingId));

  return c.json({ nonEeMeasures: rows });
});

// POST /:id/non-ee-measures
measuresRoutes.post("/:id/non-ee-measures", async (c) => {
  const buildingId = c.req.param("id");
  const body = await c.req.json().catch(() => null);
  const parsed = createNonEeMeasureSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const nonEeMeasureId = crypto.randomUUID();
  const [, [row]] = (await db.batch([
    auditEventStatement(db, c, {
      buildingId,
      entity: "non_ee_measures",
      entityId: nonEeMeasureId,
      action: "create",
      summary: { description: parsed.data.description.slice(0, 200), unitCostUsd: parsed.data.unitCostUsd },
    }),
    db
      .insert(nonEeMeasure)
      .values({ ...parsed.data, id: nonEeMeasureId, buildingId })
      .returning(),
  ])) as unknown as [unknown, (typeof nonEeMeasure.$inferSelect)[]];

  return c.json({ nonEeMeasure: row }, 201);
});

// PUT /:id/non-ee-measures/:measureId
measuresRoutes.put("/:id/non-ee-measures/:measureId", async (c) => {
  const buildingId = c.req.param("id");
  const measureId = c.req.param("measureId");
  const body = await c.req.json().catch(() => null);
  const parsed = createNonEeMeasureSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: "Invalid body", details: parsed.error.flatten() }, 400);
  }

  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  // Existence is checked up front (not via the update's own `.returning()`) so a 404 never writes
  // an audit_event — the audit statement has to go first in the batch, before we know whether the
  // WHERE actually matched a row (security.md/A09 acceptance criteria).
  const existing = await db.query.nonEeMeasure.findFirst({
    where: and(eq(nonEeMeasure.id, measureId), eq(nonEeMeasure.buildingId, buildingId)),
    columns: { id: true },
  });
  if (!existing) {
    return c.json({ error: "Not found" }, 404);
  }

  const [, [row]] = (await db.batch([
    auditEventStatement(db, c, {
      buildingId,
      entity: "non_ee_measures",
      entityId: measureId,
      action: "update",
      summary: {
        description: parsed.data.description.slice(0, 200),
        unitCostUsd: parsed.data.unitCostUsd,
      },
    }),
    db
      .update(nonEeMeasure)
      .set(parsed.data)
      .where(and(eq(nonEeMeasure.id, measureId), eq(nonEeMeasure.buildingId, buildingId)))
      .returning(),
  ])) as unknown as [unknown, (typeof nonEeMeasure.$inferSelect)[]];

  return c.json({ nonEeMeasure: row });
});

// DELETE /:id/non-ee-measures/:measureId
measuresRoutes.delete("/:id/non-ee-measures/:measureId", async (c) => {
  const buildingId = c.req.param("id");
  const measureId = c.req.param("measureId");
  const db = c.get("db");
  const user = c.get("user");

  const access = await findAccessibleBuilding(db, buildingId, user.id);
  if (!access) {
    return c.json({ error: "Not found" }, 404);
  }
  if (!canWrite(access.role)) {
    return c.json({ error: "You only have view access to this building." }, 403);
  }

  const existing = await db.query.nonEeMeasure.findFirst({
    where: and(eq(nonEeMeasure.id, measureId), eq(nonEeMeasure.buildingId, buildingId)),
    columns: { description: true, unitCostUsd: true },
  });
  if (!existing) {
    return c.json({ error: "Not found" }, 404);
  }

  await db.batch([
    auditEventStatement(db, c, {
      buildingId,
      entity: "non_ee_measures",
      entityId: measureId,
      action: "delete",
      summary: { description: existing.description.slice(0, 200), unitCostUsd: existing.unitCostUsd },
    }),
    db
      .delete(nonEeMeasure)
      .where(and(eq(nonEeMeasure.id, measureId), eq(nonEeMeasure.buildingId, buildingId))),
  ]);

  return c.body(null, 204);
});
