import { auditRun, building } from "@yres/db";
import { eq } from "drizzle-orm";
import { Hono } from "hono";
import type { AppEnv } from "../middleware/auth";

export const verifyRoutes = new Hono<AppEnv>();

/**
 * GET /:auditRunId - PUBLIC, unauthenticated (no authMiddleware — same
 * pattern as routes/climate.ts/reference.ts for reference-style public
 * data). The PDF report's cover-page QR code encodes this URL
 * (docs/report-redesign-proposal.md §8) so anyone holding a printed/PDF
 * copy can confirm it was actually generated by this platform.
 *
 * Deliberately minimal disclosure: only the building name and completion
 * date, never location/financial/technical detail — `auditRunId` being a
 * UUID makes this a capability URL (unguessable, but not access-controlled
 * the way an authenticated endpoint would be), so what it reveals must be
 * safe for anyone with the link to see, not just the report's owner.
 */
verifyRoutes.get("/:auditRunId", async (c) => {
  const auditRunId = c.req.param("auditRunId");
  const db = c.get("db");

  const [row] = await db
    .select({
      status: auditRun.status,
      completedAt: auditRun.completedAt,
      buildingName: building.name,
    })
    .from(auditRun)
    .innerJoin(building, eq(auditRun.buildingId, building.id))
    .where(eq(auditRun.id, auditRunId))
    .limit(1);

  if (!row || row.status !== "completed") {
    return c.json({ valid: false }, 404);
  }

  return c.json({
    valid: true,
    buildingName: row.buildingName,
    completedAt: row.completedAt,
  });
});
