import { auditRun, auditSnapshot, auditSnapshotReport, building } from "@yres/db";
import { eq } from "drizzle-orm";
import { Hono } from "hono";
import { z } from "zod";
import type { AppEnv } from "../middleware/auth";

export const verifyRoutes = new Hono<AppEnv>();

const snapshotIdParamSchema = z.string().uuid();

/**
 * GET /:auditRunId - PUBLIC, unauthenticated (no authMiddleware — same
 * pattern as routes/climate.ts/reference.ts for reference-style public
 * data). The PDF report's cover-page QR code encodes this URL
 * (docs/report-redesign-proposal.md §8) so anyone holding a printed/PDF
 * copy can confirm it was actually generated by this platform.
 *
 * Deliberately minimal disclosure: only the building name and completion
 * date, never location/financial/technical detail — `auditRunId` being a
 * UUID makes this a capability URL (unguessable, but not access-controlled
 * the way an authenticated endpoint would be), so what it reveals must be
 * safe for anyone with the link to see, not just the report's owner.
 *
 * **Legacy (A07):** snapshot-backed reports (A05/A06) now point their QR at
 * `/verify/s/:snapshotId` below instead — this route only remains reachable
 * for reports issued before that migration. `legacy: true` on the success
 * response lets the web page show a weaker-guarantee notice (no
 * version/hash to check, just "generated by this platform").
 */
verifyRoutes.get("/:auditRunId", async (c) => {
  const auditRunId = c.req.param("auditRunId");
  const db = c.get("db");

  const [row] = await db
    .select({
      status: auditRun.status,
      completedAt: auditRun.completedAt,
      buildingName: building.name,
    })
    .from(auditRun)
    .innerJoin(building, eq(auditRun.buildingId, building.id))
    .where(eq(auditRun.id, auditRunId))
    .limit(1);

  if (!row || row.status !== "completed") {
    return c.json({ valid: false }, 404);
  }

  return c.json({
    valid: true,
    legacy: true,
    buildingName: row.buildingName,
    completedAt: row.completedAt,
  });
});

/**
 * GET /s/:snapshotId - PUBLIC, unauthenticated, same capability-URL reasoning as `/:auditRunId`
 * above. The QR code on a snapshot-backed PDF (A06's `issue report` route) points here instead
 * of at `/:auditRunId` — it names an immutable `audit_snapshot`, not a live, ever-recomputed
 * `audit_run`, so a bank can check the exact engine/methodology version and SHA-256 that
 * produced the PDF, not just "a report with this name exists" (05 §2.2 Q2, §5.2).
 *
 * **Strict whitelist response** (security.md, 06 V8): building name, snapshot status/dates,
 * engine/methodology version, and per-language report hash/size — never location, financial
 * figures, calculated results, or any user's name/email. A `draft` snapshot (not yet submitted)
 * is treated as not-found, same as a missing id — it's a work-in-progress, not something to
 * confirm against.
 *
 * Deliberately **not** filtered by `building.deletedAt` (A03 §7, faza-2/README.md §4): a
 * verify link must keep working even after the building it describes is soft-deleted — the
 * report itself doesn't stop having been issued.
 *
 * D1 budget (database.md, ≤ 40/request): 2 queries (snapshot+building join, reports list) — no
 * session/auth lookup since this route is public.
 */
verifyRoutes.get("/s/:snapshotId", async (c) => {
  c.header("Cache-Control", "no-store");

  const parsed = snapshotIdParamSchema.safeParse(c.req.param("snapshotId"));
  if (!parsed.success) {
    return c.json({ valid: false }, 404);
  }
  const snapshotId = parsed.data;
  const db = c.get("db");

  const [snapshot] = await db
    .select({
      status: auditSnapshot.status,
      generatedAt: auditSnapshot.generatedAt,
      submittedAt: auditSnapshot.submittedAt,
      approvedAt: auditSnapshot.approvedAt,
      supersededAt: auditSnapshot.supersededAt,
      engineVersion: auditSnapshot.engineVersion,
      methodologyVersion: auditSnapshot.methodologyVersion,
      inputsSha256: auditSnapshot.inputsSha256,
      buildingName: building.name,
    })
    .from(auditSnapshot)
    .innerJoin(building, eq(auditSnapshot.buildingId, building.id))
    .where(eq(auditSnapshot.id, snapshotId))
    .limit(1);

  if (!snapshot || snapshot.status === "draft") {
    return c.json({ valid: false }, 404);
  }

  const reports = await db
    .select({
      lang: auditSnapshotReport.lang,
      sha256: auditSnapshotReport.sha256,
      sizeBytes: auditSnapshotReport.sizeBytes,
      createdAt: auditSnapshotReport.createdAt,
    })
    .from(auditSnapshotReport)
    .where(eq(auditSnapshotReport.snapshotId, snapshotId));

  return c.json({
    valid: true,
    buildingName: snapshot.buildingName,
    status: snapshot.status,
    generatedAt: snapshot.generatedAt,
    submittedAt: snapshot.submittedAt,
    approvedAt: snapshot.approvedAt,
    supersededAt: snapshot.supersededAt,
    engineVersion: snapshot.engineVersion,
    methodologyVersion: snapshot.methodologyVersion,
    inputsSha256: snapshot.inputsSha256,
    reports,
  });
});
