-- Reference data (materials, surface resistances, pipe losses, lamps, tariffs, Tashkent climate).
--> statement-breakpoint
-- Generated by scripts/build-reference-migration.ts from src/reference-data.ts. Never edit after applying.
--> statement-breakpoint
INSERT OR IGNORE INTO material (id, name, thermal_conductivity_w_per_mk) VALUES
('7ab64a27-fc95-4213-93c7-7434c984b753', 'Internal plaster', 0.7),
('e3e68ebb-2ef4-4643-888d-58f4596f0cdc', 'External plaster', 0.76),
('b6c3dff8-6384-4ff5-ad59-0652897b734c', 'Concrete', 1.92),
('71d20c1a-5768-41ba-b408-97588f66494c', 'Mineral wool (MW)', 0.038),
('46c6bb42-cba3-4214-957e-db5450b24f3c', 'EPS', 0.038),
('d359f2cd-283a-4fec-b768-0c5dbe4e9afc', 'XPS', 0.035),
('ff5636cb-fe73-4856-8d83-2b4a0470d9bc', 'Aerated concrete (YTONG)', 0.41),
('e3f13440-a23a-44b7-bb62-dddd248a1dab', 'Bricks', 0.7),
('1164178f-1525-41e9-8eb5-bd8d5658ceae', 'Expanded clay', 0.17),
('c9c59575-d7b8-405e-8530-7c494d0b642d', 'Concrete mixed with EPS (G-Sort)', 0.07),
('7f3df4ca-eddc-4cef-a329-e2dd8931c38d', 'Concrete with stones', 1.74),
('7b2eb404-c954-46c8-8cda-d1b189f4536f', 'Polystyrene concrete (Polistirolbeton)', 0.055),
('7d3f70a7-7ab2-4721-8fe1-b992eb50f33f', 'Concrete with expanded clay', 0.52),
('be01e046-8c28-4cdf-a366-11e79814626c', 'Aggregated slag (from boilers)', 0.76),
('72fdf1b9-60cd-4ff3-9008-a6923e536e73', 'Ruberoid', 0.17),
('95959e65-0983-43d1-93e8-ecce967b9d0c', 'Bitumen polymeric materials', 0.27),
('b818b5fb-8d31-4ded-8728-575709a2de1f', 'Wood (pine)', 0.29),
('7e0f46d6-2014-4052-a9b3-d150b14c4bc7', 'Mosaic', 1.74),
('6487184d-c210-40a2-8b5b-a1cf2bc3a82a', 'Marble', 2.91),
('9e2806d8-7de0-4343-9fc1-c68fbab3a126', 'Granite', 3.49),
('d396bf80-1484-4932-abdb-9fbc7c66bdd8', 'Concrete/sand mix', 0.76),
('1d812b82-2d4a-49c4-bb1f-cab566548889', 'Limestone', 0.73),
('6ba58731-ec51-4729-9217-a2ca73509867', 'Hollow bricks', 0.58),
('e371195e-0f4a-4206-a317-d53ef5e3438e', 'Linoleum', 0.35),
('ed7fd9ce-e7c5-4ca0-a52c-afb66b823b80', 'Tile', 1.1),
('f4838d91-5f23-48bc-93a8-ee962ab8e73b', 'Clay layer with straw', 0.65),
('d271ae47-b944-408c-b7d8-f67f75f78e49', 'Magnesium oxide board', 0.21),
('cd79a9f8-0121-4df7-ab68-cbc3b22ca5f5', 'Concrete hollow panels (220mm)', 1.295),
('713529df-7503-4b7a-879d-d203fa7704ec', 'Decorative stone', 2.1),
('20896984-2db5-493f-aac0-6434be5fed2d', 'Synthetic foam gasket (Sintipon)', 0.04),
('d6719ee1-4329-49f6-bb7e-0a3e0c87a313', 'Vapor/waterproofing membrane', 0.4),
('f256cc12-5225-4126-90a7-3edecaa03fcf', 'Slate sheet', 0.01),
('b5ea119d-0ecb-409f-8d9a-dff6b5d5221b', 'Gypsum (plaster)', 0.35),
('5c974674-b2c2-4b99-a9e3-7384463eff3e', 'Gypsum plasterboard (drywall)', 0.19),
('f92cce89-e419-407a-be0b-4f376c8d0540', 'Lime-sand mortar', 0.7),
('aa0e5972-bb95-4444-8b08-0c685c4a10a7', 'Parquet/laminate/linoleum flooring', 0.38),
('0007b854-8686-446c-896f-9a44bd0a2616', 'Mineral wool MW 150', 0.22);
--> statement-breakpoint
INSERT OR IGNORE INTO surface_resistance (id, element_category, interior_resistance_m2k_per_w, exterior_resistance_m2k_per_w) VALUES
('7fb10cf6-b5a8-4243-8c5c-ffc67dc0c64e', 'external_wall', 0.13, 0.04),
('c5ec6646-402e-42a2-9191-6ad3dc8b433f', 'roof', 0.1, 0.04),
('2491fbfb-ce60-448b-8938-4839605f759d', 'floor', 0.17, 0.04),
('b1d33d8c-dc17-4cf4-9f70-14c8ea122103', 'socle_heated', 0.13, 0.13),
('efa18cb5-01cb-4c9f-aa2f-32c379b4f54b', 'socle_unheated', 0.13, 0.13),
('a3bea82c-bef1-4e40-9a94-52e82d1d14a8', 'socle_ground', 0.13, 0.04);
--> statement-breakpoint
INSERT OR IGNORE INTO pipe_loss_reference (id, diameter_class, insulated, mean_fluid_temp_c, max_heat_flux_w_per_m) VALUES
('891523df-fa4b-4d8c-baea-baa0adab06d1', '15-25', 'non_insulated', NULL, 47),
('842e5d19-35be-4603-aa15-ea6687a01f77', '32-50', 'non_insulated', NULL, 74),
('fb0f6c2c-a1b8-405e-82e7-4daa4b80e160', '65-100', 'non_insulated', NULL, 140),
('8dda4368-b5c8-41f1-8141-7e4b5063225f', '15-25', 'insulated', 60, 11),
('bb4f1edb-f0e3-4838-b7b3-69440625b0ef', '32-50', 'insulated', 60, 14),
('e8aabb19-61a6-4935-833d-ede7a544aa0a', '65-100', 'insulated', 60, 19);
--> statement-breakpoint
INSERT OR IGNORE INTO lamp_type (id, name, power_density_w_per_m2) VALUES
('5b2c7994-1f81-4018-adc7-fd725cb067d0', 'Incandescent', 25),
('168a12a7-5224-4e6d-998a-32d5fcb9e43c', 'Fluorescent (electromagnetic ballast)', 17.8),
('022b5674-0475-46ea-8618-6e841e08fb7d', 'Fluorescent (electronic ballast)', 14.81),
('7a244e96-7072-4a6e-ac68-efda3e4c415f', 'LED 600×600 37W', 7.4);
--> statement-breakpoint
INSERT OR IGNORE INTO energy_tariff (id, energy_carrier, unit_cost_local, unit_cost_usd, emission_factor_kg_co2_per_kwh, primary_energy_factor, exchange_rate_local_per_usd, effective_date) VALUES
('adad99db-11af-404a-86d8-46c8c412a4ac', 'gas', 263.1578947368421, 0.0219, 0.198, 1.36, 12024, '2026-10-02'),
('2b262b00-0fe9-4ac6-a164-bcc43f7a0d22', 'electricity', 1100, 0.0915, 0.585, 2.789, 12024, '2026-10-02'),
('57658047-8343-4a05-b09f-c96d7b81bfc7', 'district_heat', 601.8916595012897, 0.0501, 0.05, 1.36, 12024, '2026-10-02'),
('a8495339-5568-4fe3-b08c-ce61071da3ee', 'coal', 187.5744, 0.0156, 0.38, 1, 12024, '2026-10-02');
--> statement-breakpoint
INSERT OR IGNORE INTO climate_region (id, name, design_outdoor_temp_c, avg_annual_temp_c, min_absolute_temp_c, max_absolute_temp_c) VALUES
('218ce97c-40b3-4b0f-92bd-34459f9a401e', 'Tashkent', -14, 14.8, -29.5, 44.6);
--> statement-breakpoint
INSERT OR IGNORE INTO climate_monthly_normal (id, month, avg_outdoor_temp_c, heating_days_in_month, is_heating_season_month, solar_radiation_south_kwh_m2, solar_radiation_north_kwh_m2, solar_radiation_east_west_kwh_m2, solar_radiation_se_sw_kwh_m2, solar_radiation_ne_nw_kwh_m2, solar_radiation_horizontal_kwh_m2, climate_region_id) VALUES
('19242376-7667-4365-8bc5-81c49df43bce', 1, -0.1, 28, 1, 65, 17.7, 28.5, 51.2, 18.7, 33.5, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('4387b4b6-7f04-4ed2-a8b9-2b1012c583f0', 2, 2.5, 25, 1, 76.3, 21.9, 38.9, 62.3, 24.4, 49.8, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('8b64ccc3-90c9-4451-a818-1f5670c88dc5', 3, 8.6, 28, 1, 96, 29.3, 61.3, 85, 37.5, 91.5, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('824530b4-145a-4be0-84e7-9bac46ed3bfb', 4, 15.3, 12, 1, 20.1, 7.9, 16.7, 20.1, 11.6, 28.3, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('3ab19dd5-0670-428a-a96b-3ee471fe12a5', 5, 20.5, NULL, 0, 31.5, 26.5, 59, 52.5, 45, 119.7, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('bce61406-b967-41ea-8f12-91b8a07a15d2', 6, 25.8, NULL, 0, 65, 54, 125, 111, 93, 244.7, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('d1aed7f3-3f5d-4d67-8db0-97f92944b0ca', 7, 27.8, NULL, 0, 68, 53, 135, 120, 98, 243.6, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('59115075-5fe4-4c94-bf0f-e4dc8a15b389', 8, 26.2, NULL, 0, 61, 44, 106, 99, 76, 204.4, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('49a6c952-3756-4a00-8d23-bb99bb950e7a', 9, 20.6, NULL, 0, 31, 17, 39.5, 41, 24.5, 81.8, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('d92b2523-dd4f-4594-a41e-a4ac8de7471d', 10, 12.4, 15, 1, 24.3, 5.8, 12.7, 20.3, 7, 19.9, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('c3b004b9-3920-426c-a02b-b8b09e84695b', 11, 6.6, 27, 1, 60.8, 13.1, 24, 48, 14.3, 37.5, '218ce97c-40b3-4b0f-92bd-34459f9a401e'),
('3cc0db1b-5972-49e7-98f9-8ecb272ccddf', 12, 1.2, 28, 1, 58.4, 11.5, 20, 44.5, 11.7, 26.7, '218ce97c-40b3-4b0f-92bd-34459f9a401e');
