CREATE TABLE `building_financial_parameters` (
	`building_id` text PRIMARY KEY NOT NULL,
	`base_year` integer NOT NULL,
	`period_years` integer NOT NULL,
	`inflation_rate` real NOT NULL,
	`real_discount_rate` real NOT NULL,
	`real_escalation_gas` real NOT NULL,
	`real_escalation_electricity` real NOT NULL,
	`real_escalation_heat` real NOT NULL,
	`exchange_rate_uzs_per_usd` real NOT NULL,
	`gas_tariff_uzs_per_m3` real NOT NULL,
	`gas_ncv_kwh_per_m3` real NOT NULL,
	`electricity_tariff_uzs_per_kwh` real NOT NULL,
	`heat_tariff_uzs_per_gcal` real NOT NULL,
	`coal_price_uzs_per_t` real,
	`coal_ncv_kwh_per_kg` real,
	`pv_export_enabled` integer DEFAULT false NOT NULL,
	`pv_export_tariff_uzs_per_kwh` real NOT NULL,
	`irr_initial_guess` real NOT NULL,
	`tariff_source` text,
	`tariff_effective_date` text,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`building_id`) REFERENCES `building`(`id`) ON UPDATE no action ON DELETE cascade
);
