/**
 * Writes the SQL of `drizzle/0001_reference_data.sql` from `src/reference-data.ts`.
 *
 *   bun run build:reference-migration [path]
 *
 * Run once when the migration is created (ids are random, so re-running yields a
 * different file) — the committed file is the artifact. A later reference-data
 * change is a NEW `generate --custom` migration, never an edit of an applied one.
 */
import { writeFileSync } from "node:fs";
import {
  CLIMATE_MONTHLY_NORMALS,
  CLIMATE_REGION,
  ENERGY_TARIFFS,
  LAMP_TYPES,
  MATERIALS,
  PIPE_LOSS_REFERENCES,
  REFERENCE_EFFECTIVE_DATE,
  SURFACE_RESISTANCES,
} from "../src/reference-data";

/** D1 statement limit is 100 KB; stay far below it. */
const MAX_STATEMENT_CHARS = 50_000;

type Row = Record<string, string | number | boolean | null | undefined>;

function literal(value: Row[string]): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`Non-finite number in reference data: ${value}`);
    return String(value);
  }
  return `'${value.replaceAll("'", "''")}'`;
}

const snake = (key: string) => key.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`);

function insertStatements(table: string, rows: Row[]): string[] {
  const first = rows[0];
  if (!first) return [];
  const keys = Object.keys(first);
  const columns = keys.map(snake).join(", ");
  const statements: string[] = [];
  let tuples: string[] = [];
  let size = 0;
  const flush = () => {
    if (tuples.length === 0) return;
    statements.push(`INSERT OR IGNORE INTO ${table} (${columns}) VALUES\n${tuples.join(",\n")};`);
    tuples = [];
    size = 0;
  };
  for (const row of rows) {
    const tuple = `(${keys.map((k) => literal(row[k])).join(", ")})`;
    if (size + tuple.length > MAX_STATEMENT_CHARS) flush();
    tuples.push(tuple);
    size += tuple.length;
  }
  flush();
  return statements;
}

const withIds = (rows: readonly Row[]) => rows.map((r) => ({ id: crypto.randomUUID(), ...r }));
const regionId = crypto.randomUUID();

const sql = [
  "-- Reference data (materials, surface resistances, pipe losses, lamps, tariffs, Tashkent climate).",
  "-- Generated by scripts/build-reference-migration.ts from src/reference-data.ts. Never edit after applying.",
  ...insertStatements("material", withIds(MATERIALS)),
  ...insertStatements("surface_resistance", withIds(SURFACE_RESISTANCES)),
  ...insertStatements("pipe_loss_reference", withIds(PIPE_LOSS_REFERENCES)),
  ...insertStatements("lamp_type", withIds(LAMP_TYPES)),
  ...insertStatements(
    "energy_tariff",
    withIds(ENERGY_TARIFFS.map((r) => ({ ...r, effectiveDate: REFERENCE_EFFECTIVE_DATE }))),
  ),
  ...insertStatements("climate_region", [{ id: regionId, ...CLIMATE_REGION }]),
  ...insertStatements(
    "climate_monthly_normal",
    withIds(CLIMATE_MONTHLY_NORMALS.map((r) => ({ ...r, climateRegionId: regionId }))),
  ),
].join("\n--> statement-breakpoint\n");

const out = process.argv[2];
if (!out) throw new Error("Usage: build-reference-migration.ts <output .sql path>");
writeFileSync(out, `${sql}\n`);
console.log(`Wrote ${out}`);
